In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[ 0.335919  , -0.71071065, -0.95715853],
       [ 1.98975931, -1.41344634,  0.18140386]])

In [4]:
data * 10

array([[  3.35919002,  -7.10710646,  -9.57158531],
       [ 19.89759311, -14.13446342,   1.81403865]])

In [5]:
data + data

array([[ 0.671838  , -1.42142129, -1.91431706],
       [ 3.97951862, -2.82689268,  0.36280773]])

In [6]:
data1 = [6,7.5,8,0,1]

In [7]:
arr1 = np.array(data1)

In [8]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
arr1.dtype

dtype('float64')

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.empty((2,3,2))

array([[[1.24392237e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23053953e-307, 5.64233733e-067]],

       [[6.20133075e-091, 3.26696493e-032],
        [2.81072484e-033, 1.48643197e-076],
        [3.99910963e+252, 2.22522596e-306]]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
test = np.array([2,3])

In [19]:
addd = np.asarray(test)

In [20]:
addd

array([2, 3])

In [23]:
delt = np.eye(2)

In [24]:
delt

array([[1., 0.],
       [0., 1.]])

In [25]:
react = np.identity(4)

In [26]:
react

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
arr3 = np.array([1,2,3],dtype=np.float64)

In [28]:
arr3

array([1., 2., 3.])

In [29]:
arr3 * arr3

array([1., 4., 9.])

In [30]:
arr3 - arr3

array([0., 0., 0.])